spring.application.name=api-plantfyth

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

server.address=0.0.0.0
server.port=${PORT:8080}

perenual.api.url=${PERENUAL_URL}
perenual.api.key=${PERENUAL_KEY}

openai.api.key=${OPENAI_KEY}
openai.api.url=${OPENAI_URL}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update