spring.application.name=api-plantfyth

spring.datasource.url=jdbc:postgresql://ep-proud-bird-ac6yhujt-pooler.sa-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_dtcCEPx6eV9a&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.passwordd=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
